import { ArrowRight } from "lucide-react";
import { Link } from "@tanstack/react-router";
import { Button } from "@/frontend/components/ui/button";
import showcase from "@/frontend/assets/advertising/grocery-advertising-showcase.png.asset.json";
import storefronts from "@/frontend/assets/advertising/kirana-storefronts.png.asset.json";
import signboard from "@/frontend/assets/advertising/illuminated-sign-board.png.asset.json";
import { EmailForm } from "@/frontend/components/forms/email-form";
import { advertisingFields } from "@/frontend/content/forms";
import { advertisingFormats } from "./content";
export function AdvertisingPageContent(){ return <>
<section className="dark-surface relative min-h-[600px] overflow-hidden"><img src={showcase.url} alt="Rishishwar grocery storefront showing product advertising placements" className="absolute inset-0 size-full object-cover"/><div className="hero-overlay-mobile absolute inset-0 md:hidden"/><div className="hero-overlay absolute inset-0 hidden md:block"/><div className="page-shell relative flex min-h-[600px] items-center py-20"><div className="max-w-2xl"><p className="royal-label">Shop Network Advertising</p><h1 className="mt-6 text-4xl leading-tight text-ink-foreground sm:text-6xl">Advertise your product <span className="text-accent-foreground">where people shop.</span></h1><p className="mt-6 max-w-xl text-lg leading-8 text-ink-foreground/75">Present your brand through selected in-store and storefront placements across our retail network.</p><Button asChild size="lg" className="mt-8"><a href="#advertising-enquiry">Plan your campaign <ArrowRight/></a></Button></div></div></section>
<section className="cinematic-section"><div className="page-shell"><div className="grid gap-10 lg:grid-cols-2 lg:items-end"><div><p className="royal-label">Available Formats</p><h2 className="mt-6 text-4xl sm:text-5xl">Two focused ways to build shop-level visibility.</h2></div><p className="leading-7 text-muted-foreground">Placement availability, locations, creative approval and commercial terms are confirmed after enquiry.</p></div><div className="mt-12 grid gap-6 md:grid-cols-2">{advertisingFormats.map(({icon:Icon,title,text})=><article key={title} className="border border-border bg-card p-6 sm:p-8"><Icon className="size-8 text-primary"/><h3 className="mt-6 text-2xl">{title}</h3><p className="mt-3 leading-7 text-muted-foreground">{text}</p></article>)}</div></div></section>
<section className="border-y border-border bg-secondary"><div className="page-shell grid lg:grid-cols-[1.3fr_0.7fr]"><img src={storefronts.url} alt="Examples of product advertising placements across kirana storefronts" className="h-full min-h-80 w-full object-cover"/><div className="flex items-center p-7 sm:p-10"><div><p className="royal-label">Network Presence</p><h2 className="mt-5 text-3xl">Built for the point of purchase.</h2><p className="mt-4 leading-7 text-muted-foreground">Storefront and in-store visibility can help shoppers notice products close to the buying decision. Final locations depend on participating-store availability.</p><Button asChild variant="outline" className="mt-6"><Link to="/store-list" search={{ state: "", area: "", district: "" }}>Explore network areas</Link></Button></div></div></div></section>
<section className="cinematic-section"><div className="page-shell grid gap-10 lg:grid-cols-[0.7fr_1.3fr] lg:items-center"><img src={signboard.url} alt="Custom illuminated sign board advertising format" className="mx-auto aspect-square w-full max-w-md object-cover"/><div id="advertising-enquiry" className="border border-border bg-card p-5 sm:p-8"><p className="royal-label">Campaign Enquiry</p><h2 className="mb-6 mt-5 text-3xl">Tell us what you want to advertise.</h2><EmailForm fields={advertisingFields} subject="Shop Advertising Enquiry" intro="I want to advertise my product across your shop network." submitLabel="Send advertising enquiry"/></div></div></section>
</>; }
