import { ArrowLeft, ArrowRight, CheckCircle2, ExternalLink } from "lucide-react";
import { Link } from "@tanstack/react-router";
import { Button } from "@/frontend/components/ui/button";
import type { MarketProfile } from "./content";
export function MarketPageContent({profile}:{profile:MarketProfile}){return <>
<section className="cinematic-section border-b border-border bg-ink text-ink-foreground"><div className="page-shell"><Link to="/global-presence" className="inline-flex items-center gap-2 text-sm text-primary"><ArrowLeft className="size-4"/>Global Presence</Link><div className="mt-8 grid gap-8 lg:grid-cols-[1fr_auto] lg:items-end"><div><p className="text-5xl" aria-hidden="true">{profile.flag}</p><h1 className="mt-5 max-w-4xl text-4xl sm:text-6xl">{profile.name === "India" ? "India" : `India–${profile.name}`} <span className="text-accent-foreground">market opportunities</span></h1><p className="mt-6 max-w-3xl text-lg leading-8 text-ink-foreground/70">{profile.intro}</p></div><Button asChild size="lg"><Link to="/contact">Discuss this market <ArrowRight/></Link></Button></div></div></section>
<section className="cinematic-section"><div className="page-shell grid gap-10 lg:grid-cols-2"><MarketList title={profile.name === "India" ? "Indian products and categories" : `From India to ${profile.name}`} items={profile.indiaToMarket}/><MarketList title={profile.name === "India" ? "International brands entering India" : `From ${profile.name} to India`} items={profile.marketToIndia}/></div></section>
<section className="cinematic-section bg-secondary"><div className="page-shell grid gap-10 lg:grid-cols-[0.8fr_1.2fr]"><div><p className="royal-label">How We Support</p><h2 className="mt-6 text-4xl">A practical route into the market.</h2></div><MarketList title="Rishishwar support" items={profile.access}/></div></section>
<section className="page-shell py-14 sm:py-20"><h2 className="text-3xl">Sources and market references</h2><p className="mt-3 max-w-2xl text-muted-foreground">Trade rules and figures can change. Review the linked source and confirm current product requirements before shipment.</p><ul className="mt-8 grid gap-4 md:grid-cols-2">{profile.sources.map((source)=><li key={source.url}><a href={source.url} target="_blank" rel="noreferrer" className="flex h-full items-start justify-between gap-4 border border-border bg-card p-5 transition-colors hover:border-primary"><span><strong className="block">{source.label}</strong><span className="mt-1 block text-sm text-muted-foreground">{source.year}</span></span><ExternalLink className="size-4 shrink-0 text-primary"/></a></li>)}</ul></section>
</>}
function MarketList({title,items}:{title:string;items:string[]}){return <div><h2 className="text-2xl sm:text-3xl">{title}</h2><ul className="mt-6 space-y-4">{items.map((item)=><li key={item} className="flex items-start gap-3 border-b border-border pb-4 leading-7"><CheckCircle2 className="mt-1 size-5 shrink-0 text-primary"/><span>{item}</span></li>)}</ul></div>}
