/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdvertiseYourProductRouteImport } from './routes/advertise-your-product'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FundYourBusinessRouteImport } from './routes/fund-your-business'
import { Route as GlobalPresenceRouteImport } from './routes/global-presence'
import { Route as ManufacturersRouteImport } from './routes/manufacturers'
import { Route as OurServicesRouteImport } from './routes/our-services'
import { Route as PartnerWithUsRouteImport } from './routes/partner-with-us'
import { Route as PaymentRouteImport } from './routes/payment'
import { Route as RegisterYourStoreRouteImport } from './routes/register-your-store'
import { Route as RetailerPartnerRouteImport } from './routes/retailer-partner'
import { Route as StoreListRouteImport } from './routes/store-list'
import { Route as GlobalPresenceMarketRouteImport } from './routes/global-presence.$market'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvertiseYourProductRoute = AdvertiseYourProductRouteImport.update({
  id: '/advertise-your-product',
  path: '/advertise-your-product',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FundYourBusinessRoute = FundYourBusinessRouteImport.update({
  id: '/fund-your-business',
  path: '/fund-your-business',
  getParentRoute: () => rootRouteImport,
} as any)
const GlobalPresenceRoute = GlobalPresenceRouteImport.update({
  id: '/global-presence',
  path: '/global-presence',
  getParentRoute: () => rootRouteImport,
} as any)
const ManufacturersRoute = ManufacturersRouteImport.update({
  id: '/manufacturers',
  path: '/manufacturers',
  getParentRoute: () => rootRouteImport,
} as any)
const OurServicesRoute = OurServicesRouteImport.update({
  id: '/our-services',
  path: '/our-services',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerWithUsRoute = PartnerWithUsRouteImport.update({
  id: '/partner-with-us',
  path: '/partner-with-us',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentRoute = PaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterYourStoreRoute = RegisterYourStoreRouteImport.update({
  id: '/register-your-store',
  path: '/register-your-store',
  getParentRoute: () => rootRouteImport,
} as any)
const RetailerPartnerRoute = RetailerPartnerRouteImport.update({
  id: '/retailer-partner',
  path: '/retailer-partner',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreListRoute = StoreListRouteImport.update({
  id: '/store-list',
  path: '/store-list',
  getParentRoute: () => rootRouteImport,
} as any)
const GlobalPresenceMarketRoute = GlobalPresenceMarketRouteImport.update({
  id: '/$market',
  path: '/$market',
  getParentRoute: () => GlobalPresenceRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/advertise-your-product': typeof AdvertiseYourProductRoute
  '/contact': typeof ContactRoute
  '/fund-your-business': typeof FundYourBusinessRoute
  '/global-presence': typeof GlobalPresenceRouteWithChildren
  '/manufacturers': typeof ManufacturersRoute
  '/our-services': typeof OurServicesRoute
  '/partner-with-us': typeof PartnerWithUsRoute
  '/payment': typeof PaymentRoute
  '/register-your-store': typeof RegisterYourStoreRoute
  '/retailer-partner': typeof RetailerPartnerRoute
  '/store-list': typeof StoreListRoute
  '/global-presence/$market': typeof GlobalPresenceMarketRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/advertise-your-product': typeof AdvertiseYourProductRoute
  '/contact': typeof ContactRoute
  '/fund-your-business': typeof FundYourBusinessRoute
  '/global-presence': typeof GlobalPresenceRouteWithChildren
  '/manufacturers': typeof ManufacturersRoute
  '/our-services': typeof OurServicesRoute
  '/partner-with-us': typeof PartnerWithUsRoute
  '/payment': typeof PaymentRoute
  '/register-your-store': typeof RegisterYourStoreRoute
  '/retailer-partner': typeof RetailerPartnerRoute
  '/store-list': typeof StoreListRoute
  '/global-presence/$market': typeof GlobalPresenceMarketRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/advertise-your-product': typeof AdvertiseYourProductRoute
  '/contact': typeof ContactRoute
  '/fund-your-business': typeof FundYourBusinessRoute
  '/global-presence': typeof GlobalPresenceRouteWithChildren
  '/manufacturers': typeof ManufacturersRoute
  '/our-services': typeof OurServicesRoute
  '/partner-with-us': typeof PartnerWithUsRoute
  '/payment': typeof PaymentRoute
  '/register-your-store': typeof RegisterYourStoreRoute
  '/retailer-partner': typeof RetailerPartnerRoute
  '/store-list': typeof StoreListRoute
  '/global-presence/$market': typeof GlobalPresenceMarketRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/advertise-your-product'
    | '/contact'
    | '/fund-your-business'
    | '/global-presence'
    | '/manufacturers'
    | '/our-services'
    | '/partner-with-us'
    | '/payment'
    | '/register-your-store'
    | '/retailer-partner'
    | '/store-list'
    | '/global-presence/$market'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/advertise-your-product'
    | '/contact'
    | '/fund-your-business'
    | '/global-presence'
    | '/manufacturers'
    | '/our-services'
    | '/partner-with-us'
    | '/payment'
    | '/register-your-store'
    | '/retailer-partner'
    | '/store-list'
    | '/global-presence/$market'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/advertise-your-product'
    | '/contact'
    | '/fund-your-business'
    | '/global-presence'
    | '/manufacturers'
    | '/our-services'
    | '/partner-with-us'
    | '/payment'
    | '/register-your-store'
    | '/retailer-partner'
    | '/store-list'
    | '/global-presence/$market'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdvertiseYourProductRoute: typeof AdvertiseYourProductRoute
  ContactRoute: typeof ContactRoute
  FundYourBusinessRoute: typeof FundYourBusinessRoute
  GlobalPresenceRoute: typeof GlobalPresenceRouteWithChildren
  ManufacturersRoute: typeof ManufacturersRoute
  OurServicesRoute: typeof OurServicesRoute
  PartnerWithUsRoute: typeof PartnerWithUsRoute
  PaymentRoute: typeof PaymentRoute
  RegisterYourStoreRoute: typeof RegisterYourStoreRoute
  RetailerPartnerRoute: typeof RetailerPartnerRoute
  StoreListRoute: typeof StoreListRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advertise-your-product': {
      id: '/advertise-your-product'
      path: '/advertise-your-product'
      fullPath: '/advertise-your-product'
      preLoaderRoute: typeof AdvertiseYourProductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fund-your-business': {
      id: '/fund-your-business'
      path: '/fund-your-business'
      fullPath: '/fund-your-business'
      preLoaderRoute: typeof FundYourBusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/global-presence': {
      id: '/global-presence'
      path: '/global-presence'
      fullPath: '/global-presence'
      preLoaderRoute: typeof GlobalPresenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manufacturers': {
      id: '/manufacturers'
      path: '/manufacturers'
      fullPath: '/manufacturers'
      preLoaderRoute: typeof ManufacturersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-services': {
      id: '/our-services'
      path: '/our-services'
      fullPath: '/our-services'
      preLoaderRoute: typeof OurServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner-with-us': {
      id: '/partner-with-us'
      path: '/partner-with-us'
      fullPath: '/partner-with-us'
      preLoaderRoute: typeof PartnerWithUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment': {
      id: '/payment'
      path: '/payment'
      fullPath: '/payment'
      preLoaderRoute: typeof PaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register-your-store': {
      id: '/register-your-store'
      path: '/register-your-store'
      fullPath: '/register-your-store'
      preLoaderRoute: typeof RegisterYourStoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/retailer-partner': {
      id: '/retailer-partner'
      path: '/retailer-partner'
      fullPath: '/retailer-partner'
      preLoaderRoute: typeof RetailerPartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store-list': {
      id: '/store-list'
      path: '/store-list'
      fullPath: '/store-list'
      preLoaderRoute: typeof StoreListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/global-presence/$market': {
      id: '/global-presence/$market'
      path: '/$market'
      fullPath: '/global-presence/$market'
      preLoaderRoute: typeof GlobalPresenceMarketRouteImport
      parentRoute: typeof GlobalPresenceRoute
    }
  }
}

interface GlobalPresenceRouteChildren {
  GlobalPresenceMarketRoute: typeof GlobalPresenceMarketRoute
}

const GlobalPresenceRouteChildren: GlobalPresenceRouteChildren = {
  GlobalPresenceMarketRoute: GlobalPresenceMarketRoute,
}

const GlobalPresenceRouteWithChildren = GlobalPresenceRoute._addFileChildren(
  GlobalPresenceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdvertiseYourProductRoute: AdvertiseYourProductRoute,
  ContactRoute: ContactRoute,
  FundYourBusinessRoute: FundYourBusinessRoute,
  GlobalPresenceRoute: GlobalPresenceRouteWithChildren,
  ManufacturersRoute: ManufacturersRoute,
  OurServicesRoute: OurServicesRoute,
  PartnerWithUsRoute: PartnerWithUsRoute,
  PaymentRoute: PaymentRoute,
  RegisterYourStoreRoute: RegisterYourStoreRoute,
  RetailerPartnerRoute: RetailerPartnerRoute,
  StoreListRoute: StoreListRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
